### ISSUE TITLE
Run code in self

### ISSUE THREAD

**Issue by amedeiros** [tario/shikashi#27]
Trying to run some user inputed code that requires some methods on a class. Is there a way to run the code in the context of another class?

```ruby
def sandbox
  sandbox = Shikashi::Sandbox.new
  priv    = Shikashi::Privileges.new
  # Trying to include self into the sandbox. This is the class I need the code to eval with.
  priv.object(self).allow(:configure)
  priv.allow_method(:method_missing)
  sandbox.run(code: @signature, privileges: priv, timeout: 30)
end

def configure
  raise Metascrape::DSLArgumentError, 'Missing required block' unless block_given?
  yield config
end
```

This is the error I get.
`NoMethodError: undefined method 'configure' for Shikashi::Sandbox::SandboxBasenamespace15267337:Module`

**Comment by amedeiros** [comment]
Also the sandbox was throwing an error if I did not allow method_missing which I thought was strange.

**Comment by tario** [comment]
Nope, you can't do that. I made it that way for some reason, but I don't remember why :( 

I think that is because the sandbox code should be insolated in a module, in order to prevent changing existing classes, for example

```ruby
class User
   def is_logged_in
       ...
   end
end
```

If the sandbox is able to run that code outside a module, then the sandbox code would be able to rewrite any method on any class, to, for example, change the behaviour of User#is_logged_in

Maybe another option is to ban class and method definitions while allowing runing code "in self", that solution fits your particular needs?

**Comment by tario** [comment]
You can use this trick (it will work on current 0.6.0 version of shikashi):
```ruby
require "shikashi"

class CustomSandbox
    def sandbox(code)
        sandbox = Shikashi::Sandbox.new
        priv    = Shikashi::Privileges.new

        priv.object(self).allow(:configure)
        priv.allow_method :print
        s = sandbox.run("class X
          def install(obj)
            def obj.run
              #{code}
            end
          end
        end", priv)

        sandbox.base_namespace::X.new.install(self)
        p self.run
    end
    
    def configure(value)
        print "configure was called with #{value} \n"
    end
    
    def is_ok
        # complex logic here
    end
end
```

but, please, have EXTREMELY CAUTIONS about using this approach, and think what would happen on ths cases, and if you would be cool with that cases:

```ruby

custom = CustomSandbox.new
custom.sandbox("def self.foo; 4; end")
p custom.foo

custom.sandbox("\nend\n def obj.foo\n 4\n") #ruby injection
p custom.foo

custom.sandbox("\nend\n def obj.is_ok\n true\n") #ruby injection
p custom.is_ok
```

Previous examples will NOT be able to break the sandbox or something like that, but they are capable of overwritting methods on your class (I named it CustomSandbox in the example), if you want to use this approach, take into account that.

My next modification is to add a simple way to ban method/singletonmethod definitions from code to avoid this method redefinition

Another drawback of this approach: the sandboxed code cannot define classes on any way

**Comment by amedeiros** [comment]
Awesome thank you for the response and some samples. I will give it a try. I like your gem and the idea behind white listing methods and constants.

**Comment by amedeiros** [comment]
This is the solution I came up with. I omitted some code but basically my class takes the ruby string and sets it up in a sandbox with a new class that inherits from the methods i need to run with the ruby string. Then i just delegate through method missing to the sandboxed object.

```ruby
# Encoding: utf-8
require 'shikashi'
include Shikashi

def initialize(ruby)
  @ruby = ruby
  # Setup the sandbox
  sandbox
  # Create a new sandboxed ruby signature
  @signature = @sandbox.base_namespace::RubySandbox.new
  @signature.eval
end

def sandbox
  @sandbox = Shikashi::Sandbox.new
  priv     = Shikashi::Privileges.new
  ALLOWED_CONSTANTS.each { |const| priv.allow_const_read(const) }
  ALLOWED_METHODS.each { |method| priv.allow_method(method) }
  
  @sandbox.run(code: "class RubySandbox < DSL::CustomSignaturesRubyBase
  def eval
    #{@ruby}
  end
end", privileges: priv, timeout: 60)
end

# Delegate to our ruby sandbox signature
def method_missing(meth, *args, &block)
  @signature.send(meth, *args, &block)
end
```

**Comment by tario** [comment]
It looks great!, even if the string break your structure with something like:
```ruby
end
end
class  ZZZ
   def foo
```
There will be no problem since the classes are inside de namespace, I am thiking of adding this to the gem, How would you like it to be used?

**Comment by amedeiros** [comment]
Is there away to whitelist the methods that Array or Hash define but not what Object defines. So just allow methods from Array and Hash, but not from Object?

**Comment by tario** [comment]
You should open separated issues for that

I thought to add a feature like that, but simply is not convenient , it would be only a feature to shoot to your own foot, something like "allow ALL methods of certain X class" sounds wrong to me, since you can change X class after that and inadvertently that method would be automatic allowed. You must implement that kind of feature by yourself (is not so hard, as you pointed with your example) and assume the risks
